trigger: 
  - main

pr:
  - main

stages:
  - template: Templates/nuget-package-stage.yml
    parameters:
      nugetPackages:
      - name: ContractOne
        folder: NuGetPackages/ContractOne
      - name: ContractTwo
        folder: NuGetPackages/ContractTwo